In [1]:
import pandas as pd
import re
import numpy as np
import matplotlib.pyplot as plt
import pandas_profiling

from selenium import webdriver
from selenium.webdriver.common.keys import Keys

In [160]:
browser = webdriver.Chrome(
    "/usr/lib/chromium-browser/chromedriver"
)
# browser = webdriver.Firefox(executable_path='C:/path/to/geckodriver.exe') au cas où geckdriver.exe n'est pas dans le path ni au même endroit
browser.get('https://www.msn.com/fr-fr/sport/football/ligue-1/statistiques-equipe/sp-vw-teamdiscipline')

In [3]:
numero = browser.find_element_by_xpath('//*[@id="soccerstatsmodule"]/div[2]/table')
numero.text  #objet Selenium

'CLASSEMENT ÉQUIPE CJ CR FC FS HJ\n1\nAngers\n49 4 449 445 51\n2\nLyon\n53 3 443 469 94\n3\nAmiens\n56 5 521 519 65\n4\nGuingamp\n58 5 485 464 54\n5\nMontpellier\n59 4 537 478 58\n6\nSt Etienne\n59 7 453 456 60\n7\nParis Saint-Germain\n64 4 474 443 92\n8\nRennes\n66 3 490 486 61\n9\nReims\n67 2 532 467 79\n10\nNîmes\n68 5 487 494 40\n11\nStrasbourg\n69 4 512 404 43\n12\nLille\n70 4 479 511 39\n13\nNantes\n70 6 493 496 77\n14\nNice\n70 5 425 518 40\n15\nDijon\n71 7 573 443 59\n16\nToulouse\n73 5 558 468 69\n17\nBordeaux\n75 5 545 496 60\n18\nCaen\n75 6 560 500 50\n19\nMarseille\n82 8 501 455 46\n20\nMonaco\n89 7 528 505 55'

In [4]:
miste_1 = numero.text.split('\n')

In [304]:
miste_1

['CLASSEMENT ÉQUIPE CJ CR FC FS HJ',
 '1',
 'Angers',
 '49 4 449 445 51',
 '2',
 'Lyon',
 '53 3 443 469 94',
 '3',
 'Amiens',
 '56 5 521 519 65',
 '4',
 'Guingamp',
 '58 5 485 464 54',
 '5',
 'Montpellier',
 '59 4 537 478 58',
 '6',
 'St Etienne',
 '59 7 453 456 60',
 '7',
 'Paris Saint-Germain',
 '64 4 474 443 92',
 '8',
 'Rennes',
 '66 3 490 486 61',
 '9',
 'Reims',
 '67 2 532 467 79',
 '10',
 'Nîmes',
 '68 5 487 494 40',
 '11',
 'Strasbourg',
 '69 4 512 404 43',
 '12',
 'Lille',
 '70 4 479 511 39',
 '13',
 'Nantes',
 '70 6 493 496 77',
 '14',
 'Nice',
 '70 5 425 518 40',
 '15',
 'Dijon',
 '71 7 573 443 59',
 '16',
 'Toulouse',
 '73 5 558 468 69',
 '17',
 'Bordeaux',
 '75 5 545 496 60',
 '18',
 'Caen',
 '75 6 560 500 50',
 '19',
 'Marseille',
 '82 8 501 455 46',
 '20',
 'Monaco',
 '89 7 528 505 55']

In [305]:
Ligue_one = []

for i in miste_1:
    Ligue_one.append(i)
        
Ligue_one

['CLASSEMENT ÉQUIPE CJ CR FC FS HJ',
 '1',
 'Angers',
 '49 4 449 445 51',
 '2',
 'Lyon',
 '53 3 443 469 94',
 '3',
 'Amiens',
 '56 5 521 519 65',
 '4',
 'Guingamp',
 '58 5 485 464 54',
 '5',
 'Montpellier',
 '59 4 537 478 58',
 '6',
 'St Etienne',
 '59 7 453 456 60',
 '7',
 'Paris Saint-Germain',
 '64 4 474 443 92',
 '8',
 'Rennes',
 '66 3 490 486 61',
 '9',
 'Reims',
 '67 2 532 467 79',
 '10',
 'Nîmes',
 '68 5 487 494 40',
 '11',
 'Strasbourg',
 '69 4 512 404 43',
 '12',
 'Lille',
 '70 4 479 511 39',
 '13',
 'Nantes',
 '70 6 493 496 77',
 '14',
 'Nice',
 '70 5 425 518 40',
 '15',
 'Dijon',
 '71 7 573 443 59',
 '16',
 'Toulouse',
 '73 5 558 468 69',
 '17',
 'Bordeaux',
 '75 5 545 496 60',
 '18',
 'Caen',
 '75 6 560 500 50',
 '19',
 'Marseille',
 '82 8 501 455 46',
 '20',
 'Monaco',
 '89 7 528 505 55']

In [306]:
li = []
for x in Ligue_one:
    li.append(x.split())
li

[['CLASSEMENT', 'ÉQUIPE', 'CJ', 'CR', 'FC', 'FS', 'HJ'],
 ['1'],
 ['Angers'],
 ['49', '4', '449', '445', '51'],
 ['2'],
 ['Lyon'],
 ['53', '3', '443', '469', '94'],
 ['3'],
 ['Amiens'],
 ['56', '5', '521', '519', '65'],
 ['4'],
 ['Guingamp'],
 ['58', '5', '485', '464', '54'],
 ['5'],
 ['Montpellier'],
 ['59', '4', '537', '478', '58'],
 ['6'],
 ['St', 'Etienne'],
 ['59', '7', '453', '456', '60'],
 ['7'],
 ['Paris', 'Saint-Germain'],
 ['64', '4', '474', '443', '92'],
 ['8'],
 ['Rennes'],
 ['66', '3', '490', '486', '61'],
 ['9'],
 ['Reims'],
 ['67', '2', '532', '467', '79'],
 ['10'],
 ['Nîmes'],
 ['68', '5', '487', '494', '40'],
 ['11'],
 ['Strasbourg'],
 ['69', '4', '512', '404', '43'],
 ['12'],
 ['Lille'],
 ['70', '4', '479', '511', '39'],
 ['13'],
 ['Nantes'],
 ['70', '6', '493', '496', '77'],
 ['14'],
 ['Nice'],
 ['70', '5', '425', '518', '40'],
 ['15'],
 ['Dijon'],
 ['71', '7', '573', '443', '59'],
 ['16'],
 ['Toulouse'],
 ['73', '5', '558', '468', '69'],
 ['17'],
 ['Bordeaux'],
 ['75', '5', '545', '496', '60'],
 ['18'],
 ['Caen'],
 ['75', '6', '560', '500', '50'],
 ['19'],
 ['Marseille'],
 ['82', '8', '501', '455', '46'],
 ['20'],
 ['Monaco'],
 ['89', '7', '528', '505', '55']]

In [307]:
li2=li[1:]
li2
li1=li[:1]
li3=[]

for sublist in li2:
    for item in sublist:
        li3.append(item)
        
li3.remove('St')
li3[36] = 'St-' + li3[36]
li3[36]

'St-Etienne'

In [308]:
li3.remove('Paris')
li3[43] = 'Paris-' + li3[43]

In [309]:
n = 7 
  
# using list comprehension ()
final = [li3[i * n:(i + 1) * n] for i in range((len(li3) + n - 1) // n )]  
print (final)

[['1', 'Angers', '49', '4', '449', '445', '51'], ['2', 'Lyon', '53', '3', '443', '469', '94'], ['3', 'Amiens', '56', '5', '521', '519', '65'], ['4', 'Guingamp', '58', '5', '485', '464', '54'], ['5', 'Montpellier', '59', '4', '537', '478', '58'], ['6', 'St-Etienne', '59', '7', '453', '456', '60'], ['7', 'Paris-Saint-Germain', '64', '4', '474', '443', '92'], ['8', 'Rennes', '66', '3', '490', '486', '61'], ['9', 'Reims', '67', '2', '532', '467', '79'], ['10', 'Nîmes', '68', '5', '487', '494', '40'], ['11', 'Strasbourg', '69', '4', '512', '404', '43'], ['12', 'Lille', '70', '4', '479', '511', '39'], ['13', 'Nantes', '70', '6', '493', '496', '77'], ['14', 'Nice', '70', '5', '425', '518', '40'], ['15', 'Dijon', '71', '7', '573', '443', '59'], ['16', 'Toulouse', '73', '5', '558', '468', '69'], ['17', 'Bordeaux', '75', '5', '545', '496', '60'], ['18', 'Caen', '75', '6', '560', '500', '50'], ['19', 'Marseille', '82', '8', '501', '455', '46'], ['20', 'Monaco', '89', '7', '528', '505', '55']]

In [310]:
# Cartons Jaunes :CJ  Cartons Rouges :CR   Fautes Commises :FC  Fautes Subies :FS  Hors-jeu  

dfC = pd.DataFrame(np.array(final),columns=["CLASSEMENT","ÉQUIPE","CJ","CR","FC","FS","HJ"])
dfC.set_index('ÉQUIPE')
dfC.to_csv('Meilleure_Carton.csv', sep=',')

In [103]:
browser.get('https://www.msn.com/fr-fr/sport/football/ligue-1/statistiques-equipe')

In [104]:
score_joueur = browser.find_element_by_xpath('//*[@id="soccerstatsmodule"]/div[2]/table')
score_joueur.text #objet Selenium

'CLASSEMENT ÉQUIPE B PD TIRS TAB PA C\n1\nParis Saint-Germain\n105 71 454 230 387 239\n2\nLyon\n70 54 508 252 458 227\n3\nLille\n68 49 392 195 366 164\n4\nMarseille\n60 44 394 170 569 225\n5\nSt Etienne\n59 40 359 177 527 225\n6\nStrasbourg\n58 43 310 157 546 157\n7\nNîmes\n57 37 396 180 474 202\n8\nRennes\n55 34 364 159 441 191\n9\nMontpellier\n53 28 393 171 539 171\n10\nNantes\n48 28 374 150 496 182\n11\nAngers\n44 27 339 154 404 166\n12\nReims\n39 27 321 138 433 164\n13\nMonaco\n38 25 340 159 527 195\n14\nToulouse\n35 16 323 133 435 159\n15\nBordeaux\n34 25 328 138 459 168\n16\nAmiens\n31 22 289 117 403 138\n17\nDijon\n31 20 348 144 423 167\n18\nNice\n30 19 320 131 313 172\n19\nCaen\n29 17 241 97 467 127\n20\nGuingamp\n28 21 297 115 565 194'

In [269]:
possession_ballon = score_joueur.text.split('\n')

WebDriverException: Message: chrome not reachable
  (Session info: chrome=75.0.3770.100)

In [286]:
possession_ballon

['CLASSEMENT ÉQUIPE B PD TIRS TAB PA C',
 '1',
 'Paris Saint-Germain',
 '105 71 454 230 387 239',
 '2',
 'Lyon',
 '70 54 508 252 458 227',
 '3',
 'Lille',
 '68 49 392 195 366 164',
 '4',
 'Marseille',
 '60 44 394 170 569 225',
 '5',
 'St Etienne',
 '59 40 359 177 527 225',
 '6',
 'Strasbourg',
 '58 43 310 157 546 157',
 '7',
 'Nîmes',
 '57 37 396 180 474 202',
 '8',
 'Rennes',
 '55 34 364 159 441 191',
 '9',
 'Montpellier',
 '53 28 393 171 539 171',
 '10',
 'Nantes',
 '48 28 374 150 496 182',
 '11',
 'Angers',
 '44 27 339 154 404 166',
 '12',
 'Reims',
 '39 27 321 138 433 164',
 '13',
 'Monaco',
 '38 25 340 159 527 195',
 '14',
 'Toulouse',
 '35 16 323 133 435 159',
 '15',
 'Bordeaux',
 '34 25 328 138 459 168',
 '16',
 'Amiens',
 '31 22 289 117 403 138',
 '17',
 'Dijon',
 '31 20 348 144 423 167',
 '18',
 'Nice',
 '30 19 320 131 313 172',
 '19',
 'Caen',
 '29 17 241 97 467 127',
 '20',
 'Guingamp',
 '28 21 297 115 565 194']

In [287]:
attaque2 = []
for x in possession_ballon:
    attaque2.append(x.split())
attaque2

[['CLASSEMENT', 'ÉQUIPE', 'B', 'PD', 'TIRS', 'TAB', 'PA', 'C'],
 ['1'],
 ['Paris', 'Saint-Germain'],
 ['105', '71', '454', '230', '387', '239'],
 ['2'],
 ['Lyon'],
 ['70', '54', '508', '252', '458', '227'],
 ['3'],
 ['Lille'],
 ['68', '49', '392', '195', '366', '164'],
 ['4'],
 ['Marseille'],
 ['60', '44', '394', '170', '569', '225'],
 ['5'],
 ['St', 'Etienne'],
 ['59', '40', '359', '177', '527', '225'],
 ['6'],
 ['Strasbourg'],
 ['58', '43', '310', '157', '546', '157'],
 ['7'],
 ['Nîmes'],
 ['57', '37', '396', '180', '474', '202'],
 ['8'],
 ['Rennes'],
 ['55', '34', '364', '159', '441', '191'],
 ['9'],
 ['Montpellier'],
 ['53', '28', '393', '171', '539', '171'],
 ['10'],
 ['Nantes'],
 ['48', '28', '374', '150', '496', '182'],
 ['11'],
 ['Angers'],
 ['44', '27', '339', '154', '404', '166'],
 ['12'],
 ['Reims'],
 ['39', '27', '321', '138', '433', '164'],
 ['13'],
 ['Monaco'],
 ['38', '25', '340', '159', '527', '195'],
 ['14'],
 ['Toulouse'],
 ['35', '16', '323', '133', '435', '159'],
 ['15'],
 ['Bordeaux'],
 ['34', '25', '328', '138', '459', '168'],
 ['16'],
 ['Amiens'],
 ['31', '22', '289', '117', '403', '138'],
 ['17'],
 ['Dijon'],
 ['31', '20', '348', '144', '423', '167'],
 ['18'],
 ['Nice'],
 ['30', '19', '320', '131', '313', '172'],
 ['19'],
 ['Caen'],
 ['29', '17', '241', '97', '467', '127'],
 ['20'],
 ['Guingamp'],
 ['28', '21', '297', '115', '565', '194']]

In [288]:
at=attaque2[1:]
at

attaque=[]

for sublist in at:
    for item in sublist:
        attaque.append(item)

attaque

attaque.remove('St')
attaque[34] = 'St-' + attaque[34]
attaque[34]
attaque.remove('Paris')
attaque[1] = 'Paris-' + attaque[1]
attaque

['1',
 'Paris-Saint-Germain',
 '105',
 '71',
 '454',
 '230',
 '387',
 '239',
 '2',
 'Lyon',
 '70',
 '54',
 '508',
 '252',
 '458',
 '227',
 '3',
 'Lille',
 '68',
 '49',
 '392',
 '195',
 '366',
 '164',
 '4',
 'Marseille',
 '60',
 '44',
 '394',
 '170',
 '569',
 '225',
 '5',
 'St-Etienne',
 '59',
 '40',
 '359',
 '177',
 '527',
 '225',
 '6',
 'Strasbourg',
 '58',
 '43',
 '310',
 '157',
 '546',
 '157',
 '7',
 'Nîmes',
 '57',
 '37',
 '396',
 '180',
 '474',
 '202',
 '8',
 'Rennes',
 '55',
 '34',
 '364',
 '159',
 '441',
 '191',
 '9',
 'Montpellier',
 '53',
 '28',
 '393',
 '171',
 '539',
 '171',
 '10',
 'Nantes',
 '48',
 '28',
 '374',
 '150',
 '496',
 '182',
 '11',
 'Angers',
 '44',
 '27',
 '339',
 '154',
 '404',
 '166',
 '12',
 'Reims',
 '39',
 '27',
 '321',
 '138',
 '433',
 '164',
 '13',
 'Monaco',
 '38',
 '25',
 '340',
 '159',
 '527',
 '195',
 '14',
 'Toulouse',
 '35',
 '16',
 '323',
 '133',
 '435',
 '159',
 '15',
 'Bordeaux',
 '34',
 '25',
 '328',
 '138',
 '459',
 '168',
 '16',
 'Amiens',
 '31',
 '22',
 '289',
 '117',
 '403',
 '138',
 '17',
 'Dijon',
 '31',
 '20',
 '348',
 '144',
 '423',
 '167',
 '18',
 'Nice',
 '30',
 '19',
 '320',
 '131',
 '313',
 '172',
 '19',
 'Caen',
 '29',
 '17',
 '241',
 '97',
 '467',
 '127',
 '20',
 'Guingamp',
 '28',
 '21',
 '297',
 '115',
 '565',
 '194']

In [289]:
n = 8
  
# using list comprehension ()
final = [attaque[i * n:(i + 1) * n] for i in range((len(attaque) + n - 1) // n )]  
print (final)

[['1', 'Paris-Saint-Germain', '105', '71', '454', '230', '387', '239'], ['2', 'Lyon', '70', '54', '508', '252', '458', '227'], ['3', 'Lille', '68', '49', '392', '195', '366', '164'], ['4', 'Marseille', '60', '44', '394', '170', '569', '225'], ['5', 'St-Etienne', '59', '40', '359', '177', '527', '225'], ['6', 'Strasbourg', '58', '43', '310', '157', '546', '157'], ['7', 'Nîmes', '57', '37', '396', '180', '474', '202'], ['8', 'Rennes', '55', '34', '364', '159', '441', '191'], ['9', 'Montpellier', '53', '28', '393', '171', '539', '171'], ['10', 'Nantes', '48', '28', '374', '150', '496', '182'], ['11', 'Angers', '44', '27', '339', '154', '404', '166'], ['12', 'Reims', '39', '27', '321', '138', '433', '164'], ['13', 'Monaco', '38', '25', '340', '159', '527', '195'], ['14', 'Toulouse', '35', '16', '323', '133', '435', '159'], ['15', 'Bordeaux', '34', '25', '328', '138', '459', '168'], ['16', 'Amiens', '31', '22', '289', '117', '403', '138'], ['17', 'Dijon', '31', '20', '348', '144', '423', '167'], ['18', 'Nice', '30', '19', '320', '131', '313', '172'], ['19', 'Caen', '29', '17', '241', '97', '467', '127'], ['20', 'Guingamp', '28', '21', '297', '115', '565', '194']]

In [290]:
# Buts : B   Passes Décisives : PD     Tirs Au But : TAB     Passes : PA    Corners : C

dfA = pd.DataFrame(np.array(final),columns=["CLASSEMENT","ÉQUIPE","B","PD", "TIRS", "TAB", "PA", "C"])
dfA.set_index('ÉQUIPE')
dfA.to_csv('Meilleur_Attaque.csv', sep=',')

In [113]:
score_gardien = browser.find_element_by_xpath('//*[@id="soccerstatsmodule"]/div[2]/table')
score_gardien.text #objet Selenium

'CLASSEMENT ÉQUIPE BC A A PC HJ\n1\nLille\n33 94 15 10 39\n2\nNice\n35 122 16 6 40\n3\nParis Saint-Germain\n35 101 17 6 92\n4\nSt Etienne\n41 115 13 9 60\n5\nBordeaux\n42 114 10 7 60\n6\nMontpellier\n42 107 12 5 58\n7\nReims\n42 111 14 7 79\n8\nLyon\n47 105 10 5 94\n9\nNantes\n48 83 8 8 77\n10\nStrasbourg\n48 102 9 9 43\n11\nAngers\n49 119 13 5 51\n12\nAmiens\n52 116 11 9 65\n13\nMarseille\n52 86 12 12 46\n14\nRennes\n52 107 11 5 61\n15\nCaen\n54 142 9 8 50\n16\nMonaco\n57 94 8 8 55\n17\nToulouse\n57 123 9 6 69\n18\nNîmes\n58 124 10 5 40\n19\nDijon\n60 113 6 3 59\n20\nGuingamp\n68 103 10 6 54'

In [292]:
gardien = score_gardien.text.split('\n')
gardien

WebDriverException: Message: chrome not reachable
  (Session info: chrome=75.0.3770.100)

In [293]:
defense = []
for x in gardien:
    defense.append(x.split())
defense

[['CLASSEMENT', 'ÉQUIPE', 'BC', 'A', 'A', 'PC', 'HJ'],
 ['1'],
 ['Lille'],
 ['33', '94', '15', '10', '39'],
 ['2'],
 ['Nice'],
 ['35', '122', '16', '6', '40'],
 ['3'],
 ['Paris', 'Saint-Germain'],
 ['35', '101', '17', '6', '92'],
 ['4'],
 ['St', 'Etienne'],
 ['41', '115', '13', '9', '60'],
 ['5'],
 ['Bordeaux'],
 ['42', '114', '10', '7', '60'],
 ['6'],
 ['Montpellier'],
 ['42', '107', '12', '5', '58'],
 ['7'],
 ['Reims'],
 ['42', '111', '14', '7', '79'],
 ['8'],
 ['Lyon'],
 ['47', '105', '10', '5', '94'],
 ['9'],
 ['Nantes'],
 ['48', '83', '8', '8', '77'],
 ['10'],
 ['Strasbourg'],
 ['48', '102', '9', '9', '43'],
 ['11'],
 ['Angers'],
 ['49', '119', '13', '5', '51'],
 ['12'],
 ['Amiens'],
 ['52', '116', '11', '9', '65'],
 ['13'],
 ['Marseille'],
 ['52', '86', '12', '12', '46'],
 ['14'],
 ['Rennes'],
 ['52', '107', '11', '5', '61'],
 ['15'],
 ['Caen'],
 ['54', '142', '9', '8', '50'],
 ['16'],
 ['Monaco'],
 ['57', '94', '8', '8', '55'],
 ['17'],
 ['Toulouse'],
 ['57', '123', '9', '6', '69'],
 ['18'],
 ['Nîmes'],
 ['58', '124', '10', '5', '40'],
 ['19'],
 ['Dijon'],
 ['60', '113', '6', '3', '59'],
 ['20'],
 ['Guingamp'],
 ['68', '103', '10', '6', '54']]

In [294]:
std=defense[1:]
std1 = []
for sublist in std:
    for item in sublist:
        std1.append(item)
        
std1.remove('St')
std1[23] = 'St-' + std1[23]
std1.remove('Paris')
std1[15] = 'Paris-' + std1[15]

In [295]:
n = 7 
  
# using list comprehension ()
final = [std1[i * n:(i + 1) * n] for i in range((len(std1) + n - 1) // n )]  
print (final)

[['1', 'Lille', '33', '94', '15', '10', '39'], ['2', 'Nice', '35', '122', '16', '6', '40'], ['3', 'Paris-Saint-Germain', '35', '101', '17', '6', '92'], ['4', 'St-Etienne', '41', '115', '13', '9', '60'], ['5', 'Bordeaux', '42', '114', '10', '7', '60'], ['6', 'Montpellier', '42', '107', '12', '5', '58'], ['7', 'Reims', '42', '111', '14', '7', '79'], ['8', 'Lyon', '47', '105', '10', '5', '94'], ['9', 'Nantes', '48', '83', '8', '8', '77'], ['10', 'Strasbourg', '48', '102', '9', '9', '43'], ['11', 'Angers', '49', '119', '13', '5', '51'], ['12', 'Amiens', '52', '116', '11', '9', '65'], ['13', 'Marseille', '52', '86', '12', '12', '46'], ['14', 'Rennes', '52', '107', '11', '5', '61'], ['15', 'Caen', '54', '142', '9', '8', '50'], ['16', 'Monaco', '57', '94', '8', '8', '55'], ['17', 'Toulouse', '57', '123', '9', '6', '69'], ['18', 'Nîmes', '58', '124', '10', '5', '40'], ['19', 'Dijon', '60', '113', '6', '3', '59'], ['20', 'Guingamp', '68', '103', '10', '6', '54']]

In [296]:
# Buts concèdès: BC      A : Arrêts    A : Matche sans But       PC : Penalties accordès     HJ : Hors-jeu

dfD = pd.DataFrame(np.array(final),columns=['CLASSEMENT', 'ÉQUIPE', 'BC', 'A', 'MB', 'PC', 'HJ'])
dfD.set_index('ÉQUIPE')
dfD.to_csv('Meilleur_Defense.csv', sep=',')

In [161]:
classment_equipe = browser.find_element_by_xpath('//*[@id="standings-16348-grid"]')
classment_equipe.text #objet Selenium

'P Équipe J V N D BP BC DB Pts Forme\n Ligue des Champions\n Tour Préliminaire de la Ligue des Champions\n Ligue Europa\n Barrage De Relégation\n Relégation\n1 Paris Saint-Germain 38 29 4 5 105 35 +70 91 GDNGGD\n2 Lille 38 22 9 7 68 33 +35 75 NGNGGD\n3 Lyon 38 21 9 8 70 47 +23 72 GGNGGG\n4 Saint-Etienne 38 19 9 10 59 41 +18 66 GGGDGN\n5 Marseille 38 18 7 13 60 52 +8 61 GDNDGG\n6 Montpellier 38 15 14 9 53 42 +11 59 GGNGND\n7 Nice 38 15 11 12 30 35 -5 56 DGNNDG\n8 Reims 38 13 16 9 39 42 -3 55 DNDDGG\n9 Nimes 38 15 8 15 57 58 -1 53 GDGGND\n10 Rennes 38 13 13 12 55 52 +3 52 DNNNGG\n11 Strasbourg 38 11 16 11 58 48 +10 49 DNNDDG\n12 Nantes 38 13 9 16 48 48 0 48 GGGNND\n13 Angers 38 10 16 12 44 49 -5 46 DNGDDN\n14 Bordeaux 38 10 11 17 34 42 -8 41 DDDDDG\n15 Amiens 38 9 11 18 31 52 -21 38 DNNNDG\n16 Toulouse 38 8 14 16 35 57 -22 38 NDNNDD\n17 Monaco 38 8 12 18 38 57 -19 36 DNDDGD\n18 Dijon 38 9 7 22 31 60 -29 34 GDDGDG\n19 Caen 38 7 12 19 29 54 -25 33 GGNGDD\n20 Guingamp 38 5 12 21 28 68 -40 27 DDNNND'

In [297]:
classment = classment_equipe.text.split('\n')
classment

['P Équipe J V N D BP BC DB Pts Forme',
 ' Ligue des Champions',
 ' Tour Préliminaire de la Ligue des Champions',
 ' Ligue Europa',
 ' Barrage De Relégation',
 ' Relégation',
 '1 Paris Saint-Germain 38 29 4 5 105 35 +70 91 GDNGGD',
 '2 Lille 38 22 9 7 68 33 +35 75 NGNGGD',
 '3 Lyon 38 21 9 8 70 47 +23 72 GGNGGG',
 '4 Saint-Etienne 38 19 9 10 59 41 +18 66 GGGDGN',
 '5 Marseille 38 18 7 13 60 52 +8 61 GDNDGG',
 '6 Montpellier 38 15 14 9 53 42 +11 59 GGNGND',
 '7 Nice 38 15 11 12 30 35 -5 56 DGNNDG',
 '8 Reims 38 13 16 9 39 42 -3 55 DNDDGG',
 '9 Nimes 38 15 8 15 57 58 -1 53 GDGGND',
 '10 Rennes 38 13 13 12 55 52 +3 52 DNNNGG',
 '11 Strasbourg 38 11 16 11 58 48 +10 49 DNNDDG',
 '12 Nantes 38 13 9 16 48 48 0 48 GGGNND',
 '13 Angers 38 10 16 12 44 49 -5 46 DNGDDN',
 '14 Bordeaux 38 10 11 17 34 42 -8 41 DDDDDG',
 '15 Amiens 38 9 11 18 31 52 -21 38 DNNNDG',
 '16 Toulouse 38 8 14 16 35 57 -22 38 NDNNDD',
 '17 Monaco 38 8 12 18 38 57 -19 36 DNDDGD',
 '18 Dijon 38 9 7 22 31 60 -29 34 GDDGDG',
 '19 Caen 38 7 12 19 29 54 -25 33 GGNGDD',
 '20 Guingamp 38 5 12 21 28 68 -40 27 DDNNND']

In [298]:
list_cl = []
for x in classment:
    list_cl.append(x.split())
list_cl

[['P', 'Équipe', 'J', 'V', 'N', 'D', 'BP', 'BC', 'DB', 'Pts', 'Forme'],
 ['Ligue', 'des', 'Champions'],
 ['Tour', 'Préliminaire', 'de', 'la', 'Ligue', 'des', 'Champions'],
 ['Ligue', 'Europa'],
 ['Barrage', 'De', 'Relégation'],
 ['Relégation'],
 ['1',
  'Paris',
  'Saint-Germain',
  '38',
  '29',
  '4',
  '5',
  '105',
  '35',
  '+70',
  '91',
  'GDNGGD'],
 ['2', 'Lille', '38', '22', '9', '7', '68', '33', '+35', '75', 'NGNGGD'],
 ['3', 'Lyon', '38', '21', '9', '8', '70', '47', '+23', '72', 'GGNGGG'],
 ['4',
  'Saint-Etienne',
  '38',
  '19',
  '9',
  '10',
  '59',
  '41',
  '+18',
  '66',
  'GGGDGN'],
 ['5', 'Marseille', '38', '18', '7', '13', '60', '52', '+8', '61', 'GDNDGG'],
 ['6',
  'Montpellier',
  '38',
  '15',
  '14',
  '9',
  '53',
  '42',
  '+11',
  '59',
  'GGNGND'],
 ['7', 'Nice', '38', '15', '11', '12', '30', '35', '-5', '56', 'DGNNDG'],
 ['8', 'Reims', '38', '13', '16', '9', '39', '42', '-3', '55', 'DNDDGG'],
 ['9', 'Nimes', '38', '15', '8', '15', '57', '58', '-1', '53', 'GDGGND'],
 ['10', 'Rennes', '38', '13', '13', '12', '55', '52', '+3', '52', 'DNNNGG'],
 ['11',
  'Strasbourg',
  '38',
  '11',
  '16',
  '11',
  '58',
  '48',
  '+10',
  '49',
  'DNNDDG'],
 ['12', 'Nantes', '38', '13', '9', '16', '48', '48', '0', '48', 'GGGNND'],
 ['13', 'Angers', '38', '10', '16', '12', '44', '49', '-5', '46', 'DNGDDN'],
 ['14', 'Bordeaux', '38', '10', '11', '17', '34', '42', '-8', '41', 'DDDDDG'],
 ['15', 'Amiens', '38', '9', '11', '18', '31', '52', '-21', '38', 'DNNNDG'],
 ['16', 'Toulouse', '38', '8', '14', '16', '35', '57', '-22', '38', 'NDNNDD'],
 ['17', 'Monaco', '38', '8', '12', '18', '38', '57', '-19', '36', 'DNDDGD'],
 ['18', 'Dijon', '38', '9', '7', '22', '31', '60', '-29', '34', 'GDDGDG'],
 ['19', 'Caen', '38', '7', '12', '19', '29', '54', '-25', '33', 'GGNGDD'],
 ['20', 'Guingamp', '38', '5', '12', '21', '28', '68', '-40', '27', 'DDNNND']]

In [299]:
a= list_cl[:1]
b= list_cl[6:]
list_cl = a + b
list_cl

[['P', 'Équipe', 'J', 'V', 'N', 'D', 'BP', 'BC', 'DB', 'Pts', 'Forme'],
 ['1',
  'Paris',
  'Saint-Germain',
  '38',
  '29',
  '4',
  '5',
  '105',
  '35',
  '+70',
  '91',
  'GDNGGD'],
 ['2', 'Lille', '38', '22', '9', '7', '68', '33', '+35', '75', 'NGNGGD'],
 ['3', 'Lyon', '38', '21', '9', '8', '70', '47', '+23', '72', 'GGNGGG'],
 ['4',
  'Saint-Etienne',
  '38',
  '19',
  '9',
  '10',
  '59',
  '41',
  '+18',
  '66',
  'GGGDGN'],
 ['5', 'Marseille', '38', '18', '7', '13', '60', '52', '+8', '61', 'GDNDGG'],
 ['6',
  'Montpellier',
  '38',
  '15',
  '14',
  '9',
  '53',
  '42',
  '+11',
  '59',
  'GGNGND'],
 ['7', 'Nice', '38', '15', '11', '12', '30', '35', '-5', '56', 'DGNNDG'],
 ['8', 'Reims', '38', '13', '16', '9', '39', '42', '-3', '55', 'DNDDGG'],
 ['9', 'Nimes', '38', '15', '8', '15', '57', '58', '-1', '53', 'GDGGND'],
 ['10', 'Rennes', '38', '13', '13', '12', '55', '52', '+3', '52', 'DNNNGG'],
 ['11',
  'Strasbourg',
  '38',
  '11',
  '16',
  '11',
  '58',
  '48',
  '+10',
  '49',
  'DNNDDG'],
 ['12', 'Nantes', '38', '13', '9', '16', '48', '48', '0', '48', 'GGGNND'],
 ['13', 'Angers', '38', '10', '16', '12', '44', '49', '-5', '46', 'DNGDDN'],
 ['14', 'Bordeaux', '38', '10', '11', '17', '34', '42', '-8', '41', 'DDDDDG'],
 ['15', 'Amiens', '38', '9', '11', '18', '31', '52', '-21', '38', 'DNNNDG'],
 ['16', 'Toulouse', '38', '8', '14', '16', '35', '57', '-22', '38', 'NDNNDD'],
 ['17', 'Monaco', '38', '8', '12', '18', '38', '57', '-19', '36', 'DNDDGD'],
 ['18', 'Dijon', '38', '9', '7', '22', '31', '60', '-29', '34', 'GDDGDG'],
 ['19', 'Caen', '38', '7', '12', '19', '29', '54', '-25', '33', 'GGNGDD'],
 ['20', 'Guingamp', '38', '5', '12', '21', '28', '68', '-40', '27', 'DDNNND']]

In [300]:
equipe = list_cl[1:]

classement_equipe_l1 = []
for sublist in equipe:
    for item in sublist:
        classement_equipe_l1.append(item)

In [301]:
classement_equipe_l1.remove('Paris')
classement_equipe_l1[1] = 'Paris-' + classement_equipe_l1[1]

In [302]:
n = 11

# using list comprehension ()
final = [classement_equipe_l1[i * n:(i + 1) * n] for i in range((len(classement_equipe_l1) + n - 1) // n )]  
print (final)

[['1', 'Paris-Saint-Germain', '38', '29', '4', '5', '105', '35', '+70', '91', 'GDNGGD'], ['2', 'Lille', '38', '22', '9', '7', '68', '33', '+35', '75', 'NGNGGD'], ['3', 'Lyon', '38', '21', '9', '8', '70', '47', '+23', '72', 'GGNGGG'], ['4', 'Saint-Etienne', '38', '19', '9', '10', '59', '41', '+18', '66', 'GGGDGN'], ['5', 'Marseille', '38', '18', '7', '13', '60', '52', '+8', '61', 'GDNDGG'], ['6', 'Montpellier', '38', '15', '14', '9', '53', '42', '+11', '59', 'GGNGND'], ['7', 'Nice', '38', '15', '11', '12', '30', '35', '-5', '56', 'DGNNDG'], ['8', 'Reims', '38', '13', '16', '9', '39', '42', '-3', '55', 'DNDDGG'], ['9', 'Nimes', '38', '15', '8', '15', '57', '58', '-1', '53', 'GDGGND'], ['10', 'Rennes', '38', '13', '13', '12', '55', '52', '+3', '52', 'DNNNGG'], ['11', 'Strasbourg', '38', '11', '16', '11', '58', '48', '+10', '49', 'DNNDDG'], ['12', 'Nantes', '38', '13', '9', '16', '48', '48', '0', '48', 'GGGNND'], ['13', 'Angers', '38', '10', '16', '12', '44', '49', '-5', '46', 'DNGDDN'], ['14', 'Bordeaux', '38', '10', '11', '17', '34', '42', '-8', '41', 'DDDDDG'], ['15', 'Amiens', '38', '9', '11', '18', '31', '52', '-21', '38', 'DNNNDG'], ['16', 'Toulouse', '38', '8', '14', '16', '35', '57', '-22', '38', 'NDNNDD'], ['17', 'Monaco', '38', '8', '12', '18', '38', '57', '-19', '36', 'DNDDGD'], ['18', 'Dijon', '38', '9', '7', '22', '31', '60', '-29', '34', 'GDDGDG'], ['19', 'Caen', '38', '7', '12', '19', '29', '54', '-25', '33', 'GGNGDD'], ['20', 'Guingamp', '38', '5', '12', '21', '28', '68', '-40', '27', 'DDNNND']]

In [303]:
dfE = pd.DataFrame(np.array(final),columns=['CLASSEMENT','Équipe', 'J', 'V', 'N', 'D', 'BP', 'BC', 'DB', 'Pts', 'Forme'])
dfE.set_index('Équipe')
dfE.to_csv('Classement.csv', sep=',')

In [3]:
df = pd.read_csv('Classement.csv')
df1 = pd.read_csv('Meilleur_Attaque.csv')
df2 = pd.read_csv('Meilleur_Defense.csv')
df3 = pd.read_csv('Meilleure_Carton.csv')

In [5]:
df

,Unnamed: 0,CLASSEMENT,Équipe,J,V,N,D,BP,BC,DB,Pts,Forme
0,0,1,Paris-Saint-Germain,38,29,4,5,105,35,70,91,GDNGGD
1,1,2,Lille,38,22,9,7,68,33,35,75,NGNGGD
2,2,3,Lyon,38,21,9,8,70,47,23,72,GGNGGG
3,3,4,Saint-Etienne,38,19,9,10,59,41,18,66,GGGDGN
4,4,5,Marseille,38,18,7,13,60,52,8,61,GDNDGG
5,5,6,Montpellier,38,15,14,9,53,42,11,59,GGNGND
6,6,7,Nice,38,15,11,12,30,35,-5,56,DGNNDG
7,7,8,Reims,38,13,16,9,39,42,-3,55,DNDDGG
8,8,9,Nimes,38,15,8,15,57,58,-1,53,GDGGND
9,9,10,Rennes,38,13,13,12,55,52,3,52,DNNNGG
10,10,11,Strasbourg,38,11,16,11,58,48,10,49,DNNDDG
11,11,12,Nantes,38,13,9,16,48,48,0,48,GGGNND
12,12,13,Angers,38,10,16,12,44,49,-5,46,DNGDDN
13,13,14,Bordeaux,38,10,11,17,34,42,-8,41,DDDDDG
14,14,15,Amiens,38,9,11,18,31,52,-21,38,DNNNDG
15,15,16,Toulouse,38,8,14,16,35,57,-22,38,NDNNDD
16,16,17,Monaco,38,8,12,18,38,57,-19,36,DNDDGD
17,17,18,Dijon,38,9,7,22,31,60,-29,34,GDDGDG
18,18,19,Caen,38,7,12,19,29,54,-25,33,GGNGDD
19,19,20,Guingamp,38,5,12,21,28,68,-40,27,DDNNND

In [6]:
df1

    Unnamed: 0  CLASSEMENT               ÉQUIPE    B  PD  TIRS  TAB   PA    C
0            0           1  Paris-Saint-Germain  105  71   454  230  387  239
1            1           2                 Lyon   70  54   508  252  458  227
2            2           3                Lille   68  49   392  195  366  164
3            3           4            Marseille   60  44   394  170  569  225
4            4           5           St-Etienne   59  40   359  177  527  225
5            5           6           Strasbourg   58  43   310  157  546  157
6            6           7                Nîmes   57  37   396  180  474  202
7            7           8               Rennes   55  34   364  159  441  191
8            8           9          Montpellier   53  28   393  171  539  171
9            9          10               Nantes   48  28   374  150  496  182
10          10          11               Angers   44  27   339  154  404  166
11          11          12                Reims   39  27   321  138  433  164
12          12          13               Monaco   38  25   340  159  527  195
13          13          14             Toulouse   35  16   323  133  435  159
14          14          15             Bordeaux   34  25   328  138  459  168
15          15          16               Amiens   31  22   289  117  403  138
16          16          17                Dijon   31  20   348  144  423  167
17          17          18                 Nice   30  19   320  131  313  172
18          18          19                 Caen   29  17   241   97  467  127
19          19          20             Guingamp   28  21   297  115  565  194

In [7]:
df2

    Unnamed: 0  CLASSEMENT               ÉQUIPE  BC    A  MB  PC  HJ
0            0           1                Lille  33   94  15  10  39
1            1           2                 Nice  35  122  16   6  40
2            2           3  Paris-Saint-Germain  35  101  17   6  92
3            3           4           St-Etienne  41  115  13   9  60
4            4           5             Bordeaux  42  114  10   7  60
5            5           6          Montpellier  42  107  12   5  58
6            6           7                Reims  42  111  14   7  79
7            7           8                 Lyon  47  105  10   5  94
8            8           9               Nantes  48   83   8   8  77
9            9          10           Strasbourg  48  102   9   9  43
10          10          11               Angers  49  119  13   5  51
11          11          12               Amiens  52  116  11   9  65
12          12          13            Marseille  52   86  12  12  46
13          13          14               Rennes  52  107  11   5  61
14          14          15                 Caen  54  142   9   8  50
15          15          16               Monaco  57   94   8   8  55
16          16          17             Toulouse  57  123   9   6  69
17          17          18                Nîmes  58  124  10   5  40
18          18          19                Dijon  60  113   6   3  59
19          19          20             Guingamp  68  103  10   6  54

In [8]:
df3

    Unnamed: 0  CLASSEMENT               ÉQUIPE  CJ  CR   FC   FS  HJ
0            0           1               Angers  49   4  449  445  51
1            1           2                 Lyon  53   3  443  469  94
2            2           3               Amiens  56   5  521  519  65
3            3           4             Guingamp  58   5  485  464  54
4            4           5          Montpellier  59   4  537  478  58
5            5           6           St-Etienne  59   7  453  456  60
6            6           7  Paris-Saint-Germain  64   4  474  443  92
7            7           8               Rennes  66   3  490  486  61
8            8           9                Reims  67   2  532  467  79
9            9          10                Nîmes  68   5  487  494  40
10          10          11           Strasbourg  69   4  512  404  43
11          11          12                Lille  70   4  479  511  39
12          12          13               Nantes  70   6  493  496  77
13          13          14                 Nice  70   5  425  518  40
14          14          15                Dijon  71   7  573  443  59
15          15          16             Toulouse  73   5  558  468  69
16          16          17             Bordeaux  75   5  545  496  60
17          17          18                 Caen  75   6  560  500  50
18          18          19            Marseille  82   8  501  455  46
19          19          20               Monaco  89   7  528  505  55

In [18]:
import random
import datetime
import webbrowser
import pyttsx3
import wikipedia
from pygame import mixer
import speech_recognition as sr
#from speech_recognition.__main__ import r, audio

In [19]:
engine = pyttsx3.init()

In [20]:
voices = engine.getProperty('voices')

In [21]:
engine.setProperty('voice', voices[1].id)

In [22]:
volume = engine.getProperty('volume')

In [23]:
engine.setProperty('volume', 10.0)

In [24]:
rate = engine.getProperty('rate')

In [25]:
engine.setProperty('rate', rate - 25)

In [26]:
# Créez des listes avec vos réponses aux questions prédéfinies.
greetings = ['Salut', 'Bonjour', 'hey', 'Hai', 'Hé!', 'Hello']
question = [' Comment vas-tu?','Comment allez vous?','Comment ça va?']
responses = ['Ok', "Je vais bien","Oui ça va"]
var1 = ['qui t\'a fait', 'qui t\'a créé']
var2 = ['J\'ai été créé par Messieurs Ibrahim D sur son ordinateur.', 'Ibrahim D', 'Un mec que je n\'ai jamais connu.','Top sympa ce monsieur']
var3 = ['quelle heure est-il', 'quel est le temps', 'heure']
var4 = ['qui êtes-vous', 'comment vous appelez-vous']
cmd1 = ['navigateur ouvert', 'ouvrir google']
cmd2 = ['jouer de la musique', 'jouer des chansons', 'jouer une chanson', 'ouvrir le lecteur de musique']
cmd3 = ['Dis une blague', 'Dis-moi une blague', 'Dis quelque chose de drôle', 'Dire quelque chose de drôle']
jokes = ['Un kangourou peut-il sauter plus haut qu\'une maison? Bien sûr, une maison ne saute pas du tout. ', 'Mon chien chassait souvent les gens à vélo. C’était tellement grave que j’ai finalement dû prendre son vélo. ','J\'ai aperçu notre pote l\'autre jour, mais il ne m\'a pas vu ,Je sais, il me l\'a dit.']
cmd4 = ['ouvrire youtube', 'je veux regarder une vidéo']
cmd5 = ['Dites-moi la météo', 'Météo', 'Qu\'en est-il de la météo']
cmd6 = ['sortie', 'fermer', 'au revoir', 'rien']
cmd7 = ['Quelle est votre couleur', 'Votre couleur']
colrep = ['ici  c\'est ?', 'qui vas gagner la ligue 1']
cmd8 = ['quelle est ta couleur préférée']
cmd9 = ['Merci']
repfr9 = ['Bienvenue', 'heureux de pouvoir vous aider']

In [ ]:
# Nous allons utiliser le moteur de reconnaissance vocale de Google. 
# Définissez les détails du moteur.

while True:
    now = datetime.datetime.now()
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Dis moi quelque chose:")
        audio = r.listen(source)
        
        
        # Reconnaissance vocale à l'aide de Google Reconnaissance vocale 
    try:
        print("Tu as dit:- " + r.recognize_google(audio), language="en")
    
    except sr.UnknownValueError:
        print("Impossible de comprendre, articule jeune homme s'il te plait")
        engine.say('Je n\'ai pas compris ça. Relancez le code')
        engine.runAndWait()

In [ ]:
if r.recognize_google(audio) in greetings:
    
    random_greeting = random.choice(greetings)
    print(random_greeting)
    engine.say(random_greeting)
    engine.runAndWait()
elif r.recognize_google(audio) in question:
    engine.say('I am fine')
    engine.runAndWait()
    print('I am fine')
elif r.recognize_google(audio) in var1:
    engine.say('I was made by edward')
    engine.runAndWait()
    reply = random.choice(var2)
    print(reply)
elif r.recognize_google(audio) in cmd9:
    print(random.choice(repfr9))
    engine.say(random.choice(repfr9))
    engine.runAndWait()
elif r.recognize_google(audio) in cmd7:
    print(random.choice(colrep))
    engine.say(random.choice(colrep))
    engine.runAndWait()
    print('It keeps changing every micro second')
    engine.say('It keeps changing every micro second')
    engine.runAndWait()
elif r.recognize_google(audio) in cmd8:
    
    print(random.choice(colrep))
    engine.say(random.choice(colrep))
    engine.runAndWait()
    print('It keeps changing every micro second')
    engine.say('It keeps changing every micro second')
    engine.runAndWait()

elif r.recognize_google(audio) in cmd2:
    mixer.init()
    mixer.music.load("C:\\Users\Edward Zion SAJI\Downloads\Mighty_God_-_Martin__Colleen_Rebeiro.55145718.wav")
    mixer.music.play()

elif r.recognize_google(audio) in var4:
    engine.say('I am edza your personal AI assistant')
    engine.runAndWait()
    
elif r.recognize_google(audio) in cmd4:
    webbrowser.open('www.youtube.com')
    
elif r.recognize_google(audio) in cmd6:
    print('see you later')
    engine.say('see you later')
    engine.runAndWait()
    exit()
    
elif r.recognize_google(audio) in cmd5:
    owm = pyowm.OWM('YOUR_API_KEY')
    observation = owm.weather_at_place('Bangalore, IN')
    observation_list = owm.weather_around_coords(12.972442, 77.580643)
    w = observation.get_weather()
    w.get_wind()
    w.get_humidity()
    w.get_temperature('celsius')
    print(w)
    print(w.get_wind())
    print(w.get_humidity())
    print(w.get_temperature('celsius'))
    engine.say(w.get_wind())
    engine.runAndWait()
    engine.say('humidity')
    engine.runAndWait()
    engine.say(w.get_humidity())
    engine.runAndWait()
    engine.say('temperature')
    engine.runAndWait()
    engine.say(w.get_temperature('celsius'))
    engine.runAndWait()
    
elif r.recognize_google(audio) in var3:

    print("Current date and time : ")
    print(now.strftime("The time is %H:%M"))
    engine.say(now.strftime("The time is %H:%M"))
    engine.runAndWait()

elif r.recognize_google(audio) in cmd1:
    webbrowser.open('www.google.com')

elif r.recognize_google(audio) in cmd3:
    jokrep = random.choice(jokes)
    engine.say(jokrep)
    engine.runAndWait()

else:
    
    engine.say("please wait")
    
    engine.runAndWait()
    
    print(wikipedia.summary(r.recognize_google(audio)))
    engine.say(wikipedia.summary(r.recognize_google(audio)))
    engine.runAndWait()
    userInput3 = input("or else search in google")
    webbrowser.open_new('www.google.com/search?q=' + userInput3)

In [25]:
from tts_watson.TtsWatson import TtsWatson

ttsWatson = TtsWatson('watson_user', 'watson_password', 'fr-FR_Renne') 
ttsWatson.play("Hello World")

SyntaxError: invalid syntax (TtsWatson.py, line 20)

In [29]:
import speech_recognition as sr
 
# Record Audio
r = sr.Recognizer()
with sr.Microphone() as source:
    print("Say something!")
audio = r.listen(source)
 
# Speech recognition using Google Speech Recognition
try:
    
# for testing purposes, we're just using the default API key
# to use another API key, use `r.recognize_google(audio, key="GOOGLE_SPEECH_RECOGNITION_API_KEY")`
# instead of `r.recognize_google(audio)`
    print("You said: " + r.recognize_google(audio))
except sr.UnknownValueError:
    print("Google Speech Recognition could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Google Speech Recognition service; {0}".format(e))

Say something!

AssertionError: Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?

In [ ]:
import pandas as pd
import numpy as np
import time
import pandas_profiling
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By


users = ['CanalFootClub']
browser = webdriver.Chrome(
    "/home/monkey/Bureau/python/chromedriver"
)

for user in users:
    # User's profile
    browser.get('https://twitter.com/' + user)

    time.sleep(0.5)

    SCROLL_PAUSE_TIME = 2

    # Get scroll height
    last_height = browser.execute_script("return document.body.scrollHeight")

    while True:
        timeline = browser.find_element_by_xpath('//*[@id="timeline"]/div/div[2]')
        # Scroll down to bottom
        browser.execute_script("window.scrollTo(0, document.body.scrollHeight)")

        # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)


        # Calculate new scriiiiiiioll height and compare with last scroll height
        new_height = browser.execute_script("return document.body.scrollHeight")


        
        # break condition
        if new_height == last_height:
            break
for x in timeline.find_elements_by_class_name('TweetTextSize');
    print(x.text)
    # Quit browser

#browser.quit()